package com.example.task_app.service;

import com.example.task_app.dto.RoleDto;
import com.example.task_app.mapper.RoleMapper;
import com.example.task_app.model.Role;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.mybatis.spring.boot.test.autoconfigure.MybatisTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Import;
import org.springframework.test.context.jdbc.Sql;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * RoleServiceの統合テスト
 * 
 * このテストでは、実際のH2データベースと連携し、
 * サービス層の挙動を検証します。
 * 
 * @MybatisTest: MyBatisのマッパーとデータベース接続をテストするためのアノテーション
 * @Import: テスト対象のServiceクラスをDIコンテナに登録
 */
@MybatisTest
@Import(RoleService.class)
class RoleServiceTest {

    @Autowired
    private RoleService roleService;

    @Autowired
    private RoleMapper roleMapper;

    /**
     * 各テストの前にデータベースをクリーンアップ
     */
    @BeforeEach
    void setUp() {
        // テーブルの全データを削除してクリーンな状態にする
        List<Role> existingRoles = roleMapper.selectAll();
        for (Role role : existingRoles) {
            roleMapper.deleteById(role.getRoleId());
        }
    }

    @Test
    @DisplayName("正常系: 新規ロールの作成が成功する")
    void createRole_NewRole_Success() {
        // Arrange: 新規ロールのDTO（roleIdはnull）
        RoleDto roleDto = new RoleDto(null, "TestRole");

        // Act: サービスメソッドを実行
        roleService.createRole(roleDto);

        // Assert: データベースからロールを取得して検証
        List<Role> roles = roleMapper.selectAll();
        assertThat(roles).hasSize(1);
        assertThat(roles.get(0).getRoleName()).isEqualTo("TestRole");
        assertThat(roles.get(0).getRoleId()).isNotNull();
    }

    @Test
    @DisplayName("正常系: 複数のロールを作成できる")
    void createRole_MultipleRoles_Success() {
        // Arrange
        RoleDto roleDto1 = new RoleDto(null, "Role1");
        RoleDto roleDto2 = new RoleDto(null, "Role2");
        RoleDto roleDto3 = new RoleDto(null, "Role3");

        // Act
        roleService.createRole(roleDto1);
        roleService.createRole(roleDto2);
        roleService.createRole(roleDto3);

        // Assert
        List<Role> roles = roleMapper.selectAll();
        assertThat(roles).hasSize(3);
        assertThat(roles).extracting(Role::getRoleName)
                .containsExactlyInAnyOrder("Role1", "Role2", "Role3");
    }

    @Test
    @DisplayName("正常系: 既存ロールの更新が成功する")
    void createRole_UpdateExistingRole_Success() {
        // Arrange: まず新規ロールを作成
        RoleDto createDto = new RoleDto(null, "OriginalName");
        roleService.createRole(createDto);

        // 作成されたロールのIDを取得
        List<Role> roles = roleMapper.selectAll();
        Integer roleId = roles.get(0).getRoleId();

        // 更新用のDTO（roleIdを指定）
        RoleDto updateDto = new RoleDto(roleId, "UpdatedName");

        // Act: 更新を実行
        roleService.createRole(updateDto);

        // Assert: 更新されたことを検証
        Role updatedRole = roleMapper.selectById(roleId);
        assertThat(updatedRole.getRoleName()).isEqualTo("UpdatedName");

        // ロールの数が増えていないことを確認
        List<Role> allRoles = roleMapper.selectAll();
        assertThat(allRoles).hasSize(1);
    }

    @Test
    @DisplayName("正常系: 日本語のロール名で作成できる")
    void createRole_JapaneseRoleName_Success() {
        // Arrange
        RoleDto roleDto = new RoleDto(null, "開発者");

        // Act
        roleService.createRole(roleDto);

        // Assert
        List<Role> roles = roleMapper.selectAll();
        assertThat(roles).hasSize(1);
        assertThat(roles.get(0).getRoleName()).isEqualTo("開発者");
    }

    @Test
    @DisplayName("正常系: 長いロール名で作成できる")
    void createRole_LongRoleName_Success() {
        // Arrange: 255文字のロール名
        String longName = "A".repeat(255);
        RoleDto roleDto = new RoleDto(null, longName);

        // Act
        roleService.createRole(roleDto);

        // Assert
        List<Role> roles = roleMapper.selectAll();
        assertThat(roles).hasSize(1);
        assertThat(roles.get(0).getRoleName()).isEqualTo(longName);
    }

    @Test
    @DisplayName("正常系: 自動生成されたIDが連番になる")
    void createRole_AutoGeneratedId_Sequential() {
        // Arrange & Act
        RoleDto roleDto1 = new RoleDto(null, "Role1");
        RoleDto roleDto2 = new RoleDto(null, "Role2");

        roleService.createRole(roleDto1);
        roleService.createRole(roleDto2);

        // Assert
        List<Role> roles = roleMapper.selectAll();
        assertThat(roles).hasSize(2);
        
        // IDが割り当てられていることを確認
        assertThat(roles.get(0).getRoleId()).isNotNull();
        assertThat(roles.get(1).getRoleId()).isNotNull();
        
        // 2つ目のIDが1つ目より大きいことを確認
        assertThat(roles.get(1).getRoleId()).isGreaterThan(roles.get(0).getRoleId());
    }
}
