spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_app
    username: user
    password: password

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.task_app.model
